import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const fullJsonPath = path.join(__dirname, '../data/sp500_full.json');

const moreStocks = [
  { symbol: 'ACGL', name: 'Arch Capital Group Ltd.', sector: 'Finance', domain: 'archgroup.com' },
  { symbol: 'AES', name: 'The AES Corporation', sector: 'Utilities', domain: 'aes.com' },
  { symbol: 'AIZ', name: 'Assurant Inc.', sector: 'Finance', domain: 'assurant.com' },
  { symbol: 'ALLE', name: 'Allegion plc', sector: 'Producer manufacturing', domain: 'allegion.com' },
  { symbol: 'AMCR', name: 'Amcor plc', sector: 'Non-energy minerals', domain: 'amcor.com' },
  { symbol: 'AOS', name: 'A. O. Smith Corporation', sector: 'Producer manufacturing', domain: 'aosmith.com' },
  { symbol: 'APA', name: 'APA Corporation', sector: 'Energy minerals', domain: 'apacorp.com' },
  { symbol: 'ARE', name: 'Alexandria Real Estate Equities', sector: 'Real estate', domain: 'are.com' },
  { symbol: 'ATO', name: 'Atmos Energy Corporation', sector: 'Utilities', domain: 'atmosenergy.com' },
  { symbol: 'AWK', name: 'American Water Works', sector: 'Utilities', domain: 'amwater.com' },
  { symbol: 'BALL', name: 'Ball Corporation', sector: 'Non-energy minerals', domain: 'ball.com' },
  { symbol: 'BBWI', name: 'Bath & Body Works Inc.', sector: 'Retail trade', domain: 'bbwinc.com' },
  { symbol: 'BG', name: 'Bunge Global SA', sector: 'Consumer non-durables', domain: 'bunge.com' },
  { symbol: 'BXP', name: 'BXP Inc.', sector: 'Real estate', domain: 'bxp.com' },
  { symbol: 'CBOE', name: 'Cboe Global Markets', sector: 'Finance', domain: 'cboe.com' },
  { symbol: 'CDW', name: 'CDW Corporation', sector: 'Technology services', domain: 'cdw.com' },
  { symbol: 'CE', name: 'Celanese Corporation', sector: 'Non-energy minerals', domain: 'celanese.com' },
  { symbol: 'CFG', name: 'Citizens Financial Group', sector: 'Finance', domain: 'citizensbank.com' },
  { symbol: 'CHRW', name: 'C.H. Robinson Worldwide', sector: 'Transportation', domain: 'chrobinson.com' },
  { symbol: 'CINF', name: 'Cincinnati Financial Corp.', sector: 'Finance', domain: 'cinfin.com' },
  { symbol: 'CLX', name: 'The Clorox Company', sector: 'Consumer non-durables', domain: 'thecloroxcompany.com' },
  { symbol: 'CMA', name: 'Comerica Incorporated', sector: 'Finance', domain: 'comerica.com' },
  { symbol: 'CMS', name: 'CMS Energy Corporation', sector: 'Utilities', domain: 'cmsenergy.com' },
  { symbol: 'CNP', name: 'CenterPoint Energy Inc.', sector: 'Utilities', domain: 'centerpointenergy.com' },
  { symbol: 'COO', name: 'The Cooper Companies Inc.', sector: 'Health technology', domain: 'coopercos.com' },
  { symbol: 'CPB', name: 'Campbell Soup Company', sector: 'Consumer non-durables', domain: 'campbellsoupcompany.com' },
  { symbol: 'CPT', name: 'Camden Property Trust', sector: 'Real estate', domain: 'camdenliving.com' },
  { symbol: 'CRL', name: 'Charles River Laboratories', sector: 'Health technology', domain: 'criver.com' },
  { symbol: 'CTLT', name: 'Catalent Inc.', sector: 'Health technology', domain: 'catalent.com' },
  { symbol: 'CZR', name: 'Caesars Entertainment Inc.', sector: 'Consumer services', domain: 'caesars.com' },
  { symbol: 'DAY', name: 'Dayforce Inc.', sector: 'Technology services', domain: 'dayforce.com' },
  { symbol: 'DGX', name: 'Quest Diagnostics Inc.', sector: 'Health services', domain: 'questdiagnostics.com' },
  { symbol: 'DHI', name: 'D.R. Horton Inc.', sector: 'Consumer services', domain: 'drhorton.com' },
  { symbol: 'DLR', name: 'Digital Realty Trust', sector: 'Real estate', domain: 'digitalrealty.com' },
  { symbol: 'DLTR', name: 'Dollar Tree Inc.', sector: 'Retail trade', domain: 'dollartree.com' },
  { symbol: 'DOV', name: 'Dover Corporation', sector: 'Producer manufacturing', domain: 'dovercorporation.com' },
  { symbol: 'DPZ', name: "Domino's Pizza Inc.", sector: 'Consumer services', domain: 'dominos.com' },
  { symbol: 'DRI', name: 'Darden Restaurants Inc.', sector: 'Consumer services', domain: 'darden.com' },
  { symbol: 'DTE', name: 'DTE Energy Company', sector: 'Utilities', domain: 'dteenergy.com' },
  { symbol: 'EBAY', name: 'eBay Inc.', sector: 'Retail trade', domain: 'ebay.com' },
  { symbol: 'EG', name: 'Everest Group Ltd.', sector: 'Finance', domain: 'everestglobal.com' },
  { symbol: 'EMN', name: 'Eastman Chemical Company', sector: 'Non-energy minerals', domain: 'eastman.com' },
  { symbol: 'EIX', name: 'Edison International', sector: 'Utilities', domain: 'edison.com' },
  { symbol: 'EPAM', name: 'EPAM Systems Inc.', sector: 'Technology services', domain: 'epam.com' },
  { symbol: 'EQR', name: 'Equity Residential', sector: 'Real estate', domain: 'equityapartments.com' },
  { symbol: 'EQT', name: 'EQT Corporation', sector: 'Energy minerals', domain: 'eqt.com' },
  { symbol: 'ERIE', name: 'Erie Indemnity Company', sector: 'Finance', domain: 'erieinsurance.com' },
  { symbol: 'ESS', name: 'Essex Property Trust', sector: 'Real estate', domain: 'essexapartmenthomes.com' },
  { symbol: 'EVRG', name: 'Evergy Inc.', sector: 'Utilities', domain: 'evergy.com' },
  { symbol: 'EW', name: 'Edwards Lifesciences', sector: 'Health technology', domain: 'edwards.com' },
  { symbol: 'EXPD', name: 'Expeditors International', sector: 'Transportation', domain: 'expeditors.com' },
  { symbol: 'EXPE', name: 'Expedia Group Inc.', sector: 'Consumer services', domain: 'expediagroup.com' },
  { symbol: 'EXR', name: 'Extra Space Storage', sector: 'Real estate', domain: 'extraspace.com' },
  { symbol: 'F', name: 'Ford Motor Company', sector: 'Consumer services', domain: 'ford.com' },
  { symbol: 'FFIV', name: 'F5 Inc.', sector: 'Technology services', domain: 'f5.com' },
  { symbol: 'FITB', name: 'Fifth Third Bancorp', sector: 'Finance', domain: '53.com' },
  { symbol: 'FMC', name: 'FMC Corporation', sector: 'Non-energy minerals', domain: 'fmc.com' },
  { symbol: 'FOXA', name: 'Fox Corporation Class A', sector: 'Consumer services', domain: 'foxcorporation.com' },
  { symbol: 'FOX', name: 'Fox Corporation Class B', sector: 'Consumer services', domain: 'foxcorporation.com' },
  { symbol: 'FRT', name: 'Federal Realty Investment Trust', sector: 'Real estate', domain: 'federalrealty.com' },
  { symbol: 'FSLR', name: 'First Solar Inc.', sector: 'Electronic technology', domain: 'firstsolar.com' },
  { symbol: 'GEN', name: 'Gen Digital Inc.', sector: 'Technology services', domain: 'gendigital.com' },
  { symbol: 'GL', name: 'Globe Life Inc.', sector: 'Finance', domain: 'globelifeinsurance.com' },
  { symbol: 'GM', name: 'General Motors Company', sector: 'Consumer services', domain: 'gm.com' },
  { symbol: 'GNRC', name: 'Generac Holdings Inc.', sector: 'Producer manufacturing', domain: 'generac.com' },
  { symbol: 'GPC', name: 'Genuine Parts Company', sector: 'Retail trade', domain: 'genpt.com' },
  { symbol: 'GRMN', name: 'Garmin Ltd.', sector: 'Electronic technology', domain: 'garmin.com' },
  { symbol: 'GWW', name: 'W.W. Grainger Inc.', sector: 'Producer manufacturing', domain: 'grainger.com' },
  { symbol: 'HAL', name: 'Halliburton Company', sector: 'Energy minerals', domain: 'halliburton.com' },
  { symbol: 'HAS', name: 'Hasbro Inc.', sector: 'Consumer non-durables', domain: 'hasbro.com' },
  { symbol: 'HBAN', name: 'Huntington Bancshares Inc.', sector: 'Finance', domain: 'huntington.com' },
  { symbol: 'HES', name: 'Hess Corporation', sector: 'Energy minerals', domain: 'hess.com' },
  { symbol: 'HIG', name: 'The Hartford Financial Services Group', sector: 'Finance', domain: 'thehartford.com' },
  { symbol: 'HII', name: 'Huntington Ingalls Industries', sector: 'Producer manufacturing', domain: 'hii.com' },
  { symbol: 'HOLX', name: 'Hologic Inc.', sector: 'Health technology', domain: 'hologic.com' },
  { symbol: 'HPE', name: 'Hewlett Packard Enterprise Co.', sector: 'Electronic technology', domain: 'hpe.com' },
  { symbol: 'HPQ', name: 'HP Inc.', sector: 'Electronic technology', domain: 'hp.com' },
  { symbol: 'HRL', name: 'Hormel Foods Corporation', sector: 'Consumer non-durables', domain: 'hormelfoods.com' },
  { symbol: 'HST', name: 'Host Hotels & Resorts Inc.', sector: 'Real estate', domain: 'hosthotels.com' },
  { symbol: 'HUBB', name: 'Hubbell Incorporated', sector: 'Producer manufacturing', domain: 'hubbell.com' },
  { symbol: 'INCY', name: 'Incyte Corporation', sector: 'Health technology', domain: 'incyte.com' },
  { symbol: 'INVH', name: 'Invitation Homes Inc.', sector: 'Real estate', domain: 'invitationhomes.com' },
  { symbol: 'IPG', name: 'The Interpublic Group of Companies', sector: 'Commercial services', domain: 'interpublic.com' },
  { symbol: 'IQV', name: 'IQVIA Holdings Inc.', sector: 'Health technology', domain: 'iqvia.com' },
  { symbol: 'IR', name: 'Ingersoll Rand Inc.', sector: 'Producer manufacturing', domain: 'ingersollrand.com' },
  { symbol: 'IRM', name: 'Iron Mountain Incorporated', sector: 'Real estate', domain: 'ironmountain.com' },
  { symbol: 'IT', name: 'Gartner Inc.', sector: 'Technology services', domain: 'gartner.com' },
  { symbol: 'JBHT', name: 'J.B. Hunt Transport Services', sector: 'Transportation', domain: 'jbhunt.com' },
  { symbol: 'JKHY', name: 'Jack Henry & Associates Inc.', sector: 'Technology services', domain: 'jackhenry.com' },
  { symbol: 'JNPR', name: 'Juniper Networks Inc.', sector: 'Electronic technology', domain: 'juniper.net' },
  { symbol: 'KDP', name: 'Keurig Dr Pepper Inc.', sector: 'Consumer non-durables', domain: 'keurigdrpepper.com' },
  { symbol: 'KEY', name: 'KeyCorp', sector: 'Finance', domain: 'key.com' },
  { symbol: 'KEYS', name: 'Keysight Technologies Inc.', sector: 'Electronic technology', domain: 'keysight.com' },
  { symbol: 'KIM', name: 'Kimco Realty Corporation', sector: 'Real estate', domain: 'kimcorealty.com' },
  { symbol: 'KKR', name: 'KKR & Co. Inc.', sector: 'Finance', domain: 'kkr.com' },
  { symbol: 'KR', name: 'The Kroger Co.', sector: 'Retail trade', domain: 'thekrogerco.com' },
  { symbol: 'KVUE', name: 'Kenvue Inc.', sector: 'Consumer non-durables', domain: 'kenvue.com' },
  { symbol: 'LEN', name: 'Lennar Corporation', sector: 'Consumer services', domain: 'lennar.com' },
  { symbol: 'LH', name: 'Laboratory Corporation of America', sector: 'Health services', domain: 'labcorp.com' },
  { symbol: 'LHX', name: 'L3Harris Technologies Inc.', sector: 'Producer manufacturing', domain: 'l3harris.com' },
  { symbol: 'LKQ', name: 'LKQ Corporation', sector: 'Retail trade', domain: 'lkqcorp.com' },
  { symbol: 'LNT', name: 'Alliant Energy Corporation', sector: 'Utilities', domain: 'alliantenergy.com' },
  { symbol: 'LULU', name: 'Lululemon Athletica Inc.', sector: 'Consumer non-durables', domain: 'lululemon.com' },
  { symbol: 'LUV', name: 'Southwest Airlines Co.', sector: 'Transportation', domain: 'southwest.com' },
  { symbol: 'LYB', name: 'LyondellBasell Industries N.V.', sector: 'Non-energy minerals', domain: 'lyondellbasell.com' },
  { symbol: 'LYV', name: 'Live Nation Entertainment Inc.', sector: 'Consumer services', domain: 'livenationentertainment.com' },
  { symbol: 'MAA', name: 'Mid-America Apartment Communities', sector: 'Real estate', domain: 'maac.com' },
  { symbol: 'MAS', name: 'Masco Corporation', sector: 'Producer manufacturing', domain: 'masco.com' },
  { symbol: 'MGM', name: 'MGM Resorts International', sector: 'Consumer services', domain: 'mgmresorts.com' },
  { symbol: 'MHK', name: 'Mohawk Industries Inc.', sector: 'Consumer non-durables', domain: 'mohawkind.com' },
  { symbol: 'MKC', name: 'McCormick & Company Inc.', sector: 'Consumer non-durables', domain: 'mccormickcorporation.com' },
  { symbol: 'MKTX', name: 'MarketAxess Holdings Inc.', sector: 'Finance', domain: 'marketaxess.com' },
  { symbol: 'MLM', name: 'Martin Marietta Materials', sector: 'Non-energy minerals', domain: 'martinmarietta.com' },
  { symbol: 'MOH', name: 'Molina Healthcare Inc.', sector: 'Health services', domain: 'molinahealthcare.com' },
  { symbol: 'MOS', name: 'The Mosaic Company', sector: 'Non-energy minerals', domain: 'mosaicco.com' },
  { symbol: 'MSI', name: 'Motorola Solutions Inc.', sector: 'Electronic technology', domain: 'motorolasolutions.com' },
  { symbol: 'MTB', name: 'M&T Bank Corporation', sector: 'Finance', domain: 'mtb.com' },
  { symbol: 'MTCH', name: 'Match Group Inc.', sector: 'Technology services', domain: 'mtch.com' },
  { symbol: 'NDSN', name: 'Nordson Corporation', sector: 'Producer manufacturing', domain: 'nordson.com' },
  { symbol: 'NI', name: 'NiSource Inc.', sector: 'Utilities', domain: 'nisource.com' },
  { symbol: 'NRG', name: 'NRG Energy Inc.', sector: 'Utilities', domain: 'nrg.com' },
  { symbol: 'NVR', name: 'NVR Inc.', sector: 'Consumer services', domain: 'nvrinc.com' },
  { symbol: 'NWL', name: 'Newell Brands Inc.', sector: 'Consumer non-durables', domain: 'newellbrands.com' },
  { symbol: 'NWS', name: 'News Corporation Class B', sector: 'Consumer services', domain: 'newscorp.com' },
  { symbol: 'NWSA', name: 'News Corporation Class A', sector: 'Consumer services', domain: 'newscorp.com' },
  { symbol: 'OMC', name: 'Omnicom Group Inc.', sector: 'Commercial services', domain: 'omnicomgroup.com' },
  { symbol: 'PARA', name: 'Paramount Global', sector: 'Consumer services', domain: 'paramount.com' },
  { symbol: 'PAYC', name: 'Paycom Software Inc.', sector: 'Technology services', domain: 'paycom.com' },
  { symbol: 'PCG', name: 'PG&E Corporation', sector: 'Utilities', domain: 'pgecorp.com' },
  { symbol: 'PFG', name: 'Principal Financial Group', sector: 'Finance', domain: 'principal.com' },
  { symbol: 'PHM', name: 'PulteGroup Inc.', sector: 'Consumer services', domain: 'pultegroup.com' },
  { symbol: 'POOL', name: 'Pool Corporation', sector: 'Retail trade', domain: 'poolcorp.com' },
  { symbol: 'PWR', name: 'Quanta Services Inc.', sector: 'Producer manufacturing', domain: 'quantaservices.com' },
  { symbol: 'REG', name: 'Regency Centers Corporation', sector: 'Real estate', domain: 'regencycenters.com' },
  { symbol: 'RF', name: 'Regions Financial Corp.', sector: 'Finance', domain: 'regions.com' },
  { symbol: 'RL', name: 'Ralph Lauren Corporation', sector: 'Consumer non-durables', domain: 'ralphlauren.com' },
  { symbol: 'ROL', name: 'Rollins Inc.', sector: 'Commercial services', domain: 'rollins.com' },
  { symbol: 'SEDG', name: 'SolarEdge Technologies', sector: 'Electronic technology', domain: 'solaredge.com' },
  { symbol: 'SEE', name: 'Sealed Air Corporation', sector: 'Non-energy minerals', domain: 'sealedair.com' },
  { symbol: 'SNA', name: 'Snap-on Incorporated', sector: 'Producer manufacturing', domain: 'snapon.com' },
  { symbol: 'STE', name: 'STERIS plc', sector: 'Health technology', domain: 'steris.com' },
  { symbol: 'STLD', name: 'Steel Dynamics Inc.', sector: 'Non-energy minerals', domain: 'steeldynamics.com' },
  { symbol: 'STT', name: 'State Street Corporation', sector: 'Finance', domain: 'statestreet.com' },
  { symbol: 'SYF', name: 'Synchrony Financial', sector: 'Finance', domain: 'synchrony.com' },
  { symbol: 'TAP', name: 'Molson Coors Beverage Co.', sector: 'Consumer non-durables', domain: 'molsoncoors.com' },
  { symbol: 'TDY', name: 'Teledyne Technologies Inc.', sector: 'Electronic technology', domain: 'teledyne.com' },
  { symbol: 'TECH', name: 'Bio-Techne Corporation', sector: 'Health technology', domain: 'bio-techne.com' },
  { symbol: 'TFX', name: 'Teleflex Incorporated', sector: 'Health technology', domain: 'teleflex.com' },
  { symbol: 'TROW', name: 'T. Rowe Price Group Inc.', sector: 'Finance', domain: 'troweprice.com' },
  { symbol: 'TTWO', name: 'Take-Two Interactive Software', sector: 'Technology services', domain: 'take2games.com' },
  { symbol: 'UHS', name: 'Universal Health Services', sector: 'Health services', domain: 'uhs.com' },
  { symbol: 'VFC', name: 'V.F. Corporation', sector: 'Consumer non-durables', domain: 'vfc.com' },
  { symbol: 'VTR', name: 'Ventas Inc.', sector: 'Real estate', domain: 'ventasreit.com' },
  { symbol: 'WAB', name: 'Westinghouse Air Brake Technologies', sector: 'Producer manufacturing', domain: 'wabteccorp.com' },
  { symbol: 'WAT', name: 'Waters Corporation', sector: 'Health technology', domain: 'waters.com' },
  { symbol: 'WHR', name: 'Whirlpool Corporation', sector: 'Consumer non-durables', domain: 'whirlpoolcorp.com' },
  { symbol: 'WRB', name: 'W. R. Berkley Corporation', sector: 'Finance', domain: 'berkley.com' },
  { symbol: 'WST', name: 'West Pharmaceutical Services', sector: 'Health technology', domain: 'westpharma.com' },
  { symbol: 'WTW', name: 'Willis Towers Watson', sector: 'Finance', domain: 'wtwco.com' },
  { symbol: 'ZBH', name: 'Zimmer Biomet Holdings Inc.', sector: 'Health technology', domain: 'zimmerbiomet.com' },
  { symbol: 'ZBRA', name: 'Zebra Technologies Corporation', sector: 'Electronic technology', domain: 'zebra.com' }
];

const full = JSON.parse(fs.readFileSync(fullJsonPath, 'utf8'));
const seen = new Set(full.map(s => s.symbol));
let added = 0;
for (const stock of moreStocks) {
  if (!seen.has(stock.symbol)) {
    seen.add(stock.symbol);
    full.push(stock);
    added++;
  }
}

fs.writeFileSync(fullJsonPath, JSON.stringify(full, null, 2));
console.log(`[Expand] Added ${added} stocks. Total sp500_full: ${full.length}`);
